language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t hdw0903/my-express .
script:
  - docker run -e CI=true hdw0903/my-express npm run test
after_success:
  - docker build -t hdw0903/my-express .
  - docker build -t hdw0903/my-express-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push hdw0903/my-express
  - docker push hdw0903/my-express-nginx
